# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: ubuntu:latest

pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Dash Enterprise'
        deployment: production
        trigger: 'automatic'
        checkout: self
        script:
          - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
          - apt-get install -y git
          - git remote -v
          - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
          - cat ~/.ssh/id_rsa
          - chmod 600 ~/.ssh/id_rsa # permissioning
          - eval "$(ssh-agent -s)" # setting ssh environment variable
          - echo '-----> Adding keys to ssh-agent'
          - ssh-add ~/.ssh/id_rsa
          - echo "$SSH_CONFIG" | base64 -d > ~/.ssh/config 
          - echo '-----> Adding git remote'
          - git config remote.plotly.url >&- || git remote add plotly dokku@dash-customer-success.plotly.host:bitbucket-test
          - echo '-----> Deploying app'
          - echo "$(git remote -v)"
          - echo "$(git branch)"
          - git checkout -b runner-branch
          - GIT_SSH_COMMAND='ssh -vvv' git push plotly runner-branch:main -f
